# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3b7b7c9fea61ebe2accb6b0bff50c5a0a7f260daae1a2b22eba962512b3fb12e3ddbebf650ec1180f7e9660d505ebc03ba298257ad5b05d287286415ad4f41

test:
  secret_key_base: 5844dfddc4606baeb277ea1a69d9d850f6789e3c73680a213545d08d0dcb15655fc2cda40943fe006653e1789f2aa2da93ded06e34e2aabc1fa03eb116bcc54b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
